language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sudo apt-get install xsel"
install:
  - python setup.py -q install
# command to run tests
script: python setup.py nosetests --with-doctest --verbosity=2
