#! /usr/bin/env python
import argparse
import os
import sys

from sdb.passwords import InteractiveSession, agent_action


def add_domain(p):
    p.add_argument(
        'domain',
        nargs='?',
        help="The domain or search query for the record. "
             "Optional, will be prompted for if not given.",
        metavar='DOMAIN')

parser = argparse.ArgumentParser()
parser.add_argument('--file', default=os.path.expanduser('~/.passwords'))
parser.add_argument('--gpg-agent-info',
                    default=os.path.expanduser('~/.gpg-agent-info'),
                    help="Path to gpg-agent env file")

subparsers = parser.add_subparsers(title='commands', dest='command')

add_parser = subparsers.add_parser('add', help="Add a record.")
add_domain(add_parser)

show_parser = subparsers.add_parser(
    'show',
    help="Show a record and add its password to the clipboard. The default action.")
add_domain(show_parser)

edit_parser = subparsers.add_parser('edit', help="Edit a record.")
add_domain(edit_parser)

delete_parser = subparsers.add_parser('delete', help="Delete a record.")
add_domain(delete_parser)

raw_parser = subparsers.add_parser(
    'raw',
    help="Show all records in the on-disk format.")

agent_parser = subparsers.add_parser(
    'agent',
    help="Start a gpg-agent")


actions = ['add', 'show', 'edit', 'delete', 'raw', 'agent']
argv = sys.argv[1:]
if not any(i in argv for i in actions):
    argv.append('show')

args = parser.parse_args(argv)
if args.command == 'agent':
    # the only action that doesn't need a password
    agent_action(args)
else:
    session = InteractiveSession(args)
    commands = {
        'add': session.add_action,
        'edit': session.edit_action,
        'delete': session.delete_action,
        'raw': session.raw_action,
        'show': session.show_action,
    }

    try:
        commands[args.command]()
    except KeyboardInterrupt:
        pass
