#! /usr/bin/env python
import argparse
import os
import operator
import sys


from sdb.passwords import InteractiveSession

parser = argparse.ArgumentParser()
parser.add_argument('domain', nargs='?')
parser.add_argument('--add', action="store_true")
parser.add_argument('--edit', action="store_true")
parser.add_argument('--delete', action="store_true")
parser.add_argument('--raw', action="store_true")
parser.add_argument('--file', default=os.path.expanduser('~/.passwords'))

args = parser.parse_args()
actions = [args.edit, args.add, args.delete, args.raw]
if sum(actions) > 1:
    parser.print_usage()
    sys.stderr.write("Only one of --edit, --add, --delete, or --raw may be specified\n")
    sys.exit(2)

session = InteractiveSession(args)

try:
    if args.add:
        session.add_action()
    elif args.edit:
        session.edit_action()
    elif args.delete:
        session.delete_action()
    elif args.raw:
        session.raw_action()
    else:
        session.show_action()
except KeyboardInterrupt:
    pass
